{
# 公众号配置
# 公众号appId
"app_id": "wx7215668cc4a5558f",
# 公众号appSecret
"app_secret": "b715f745b96e50f53060e15d83143035",
# 模板消息id
"template_id": "CWYOoLbngGffsrG01FcIHJfmrB7Jg9v5gt_5DpMR01E",
# 接收公众号消息的微信号，如果有多个，需要在[]里用英文逗号间隔，例如["wx1", "wx2"]
"user": ["op_CK5om0QVnee1igNN9gxIWUCCM"],

# 信息配置
# 所在省份
"province": "四川",
# 所在城市
"city": "成都",
# 生日1，修改name为对应需要显示的名字，如果生日为农历，在最前面加上r即可
"birthday1": {"name": "拾柒", "birthday": "r2004-1-5"},
# 热爱生活的日子，格式同上
"love_date": "2004-01-26"
}
